// Worker entry point: the OpenNext-generated fetch handler, plus a `scheduled`
// handler that runs the /api/cron/* routes from Cloudflare Cron Triggers.
// See https://opennext.js.org/cloudflare/howtos/custom-worker
//
// Each scheduled route is invoked in-process through the same fetch handler,
// with the same Bearer CRON_SECRET the GitHub workflows sent, so the routes
// themselves (auth, batching, claiming) are unchanged. Nothing leaves the
// worker: no public HTTP round trip, and no secret on the wire.

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { routesFor, type CronRoute } from "./lib/cron/schedule";

// Minimal local shapes so this file type-checks inside `next build` without
// pulling @cloudflare/workers-types into the Next.js program.
type Env = { CRON_SECRET?: string } & Record<string, unknown>;
type Ctx = { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void };
type Controller = { cron: string; scheduledTime: number };
type FetchHandler = (request: Request, env: Env, ctx: Ctx) => Promise<Response>;

const fetchHandler = (handler as { fetch: FetchHandler }).fetch;

// Same host the GitHub workflows called; only used to build the Request URL.
const ORIGIN = "https://aqarbooks.com";

async function runRoute(route: CronRoute, env: Env, ctx: Ctx): Promise<void> {
  const started = Date.now();
  const request = new Request(`${ORIGIN}/api/cron/${route}`, {
    method: "POST",
    headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` },
  });
  const response = await fetchHandler(request, env, ctx);
  const body = (await response.text()).slice(0, 500);
  console.log(JSON.stringify({ cron: route, status: response.status, ms: Date.now() - started, body }));
  if (!response.ok) throw new Error(`${route} returned ${response.status}`);
}

const worker = {
  fetch: fetchHandler,

  async scheduled(controller: Controller, env: Env, ctx: Ctx): Promise<void> {
    if (!env.CRON_SECRET) {
      // The routes would answer 503 anyway; fail loudly once instead.
      throw new Error("CRON_SECRET is not set on the worker; scheduled jobs refused");
    }
    const routes = routesFor(controller.cron, controller.scheduledTime);
    const results = await Promise.allSettled(routes.map((route) => runRoute(route, env, ctx)));
    const failed = results.filter((result) => result.status === "rejected");
    // Throwing marks the invocation as failed in the Cloudflare dashboard/logs,
    // the equivalent of the red run the GitHub workflow used to produce.
    if (failed.length > 0) {
      throw new AggregateError(
        failed.map((result) => (result as PromiseRejectedResult).reason),
        `${failed.length} of ${routes.length} scheduled route(s) failed`,
      );
    }
  },
};

export default worker;
