#!/usr/bin/env node
// Builds ONE self-aborting SQL script that applies the owner-portal migration
// and the acceptance checks inside a single transaction, then ends with an
// exception so that nothing is ever committed.
//
//   node scripts/hosted-verify/build.mjs > owner-portal-access.hosted-verify.sql
//
// Paste the output into the Supabase SQL editor of the project you want to
// verify (or run it with psql). Expected outcome: an error whose message starts
// with VERIFICATION_ROLLED_BACK and carries {"failed":0,"checks":[...]}.
// Any other error also rolls everything back (the connection ends the
// transaction) -- the database is left exactly as it was.
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..", "..");
const migration = readFileSync(join(root, "supabase/migrations/20261004120000_owner_portal_access.sql"), "utf8")
  .replace(/^begin;\s*$/m, "-- (begin; removed: the wrapper owns the transaction)")
  .replace(/^commit;\s*$/m, "-- (commit; removed: this script never commits)");
if (/^\s*commit\s*;/im.test(migration)) throw new Error("migration still contains a COMMIT");
const body = readFileSync(join(import.meta.dirname, "verify-body.sql"), "utf8");

process.stdout.write(
  [
    "-- GENERATED by scripts/hosted-verify/build.mjs -- never commits.",
    "begin;",
    "set local lock_timeout = '3s';",
    "set local statement_timeout = '120s';",
    migration,
    body,
  ].join("\n"),
);
